### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by fiserjCN** [applanga/setup-applanga-cli#3]
Hello, I start to get following warning on our github action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: applanga/setup-applanga-cli

Hopefully it will be just about increasing the version in action.yml file, right? :)

**Comment by ChristianStanke** [comment]
Thank you for the report! We will look into it

**Comment by fiserjCN** [comment]
Resolved in version 1.0.2
